version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billar_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel
    command: bash -c "composer install && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: billar_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: billar_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: billar
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
